service: hello-lambda-env-public

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    MESSAGE: ${file(./src/message.json):message}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
    deploymentSettings:
      type: AllAtOnce
      alias: live

custom:
  esbuild:
    minify: false
    bundle: true
    sourcemap: true
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.serverless/**/*', '.build', '.esbuild']
    packager: yarn
  output:
    file: stack.json

plugins:
  - serverless-esbuild
  - serverless-offline
  # - serverless-plugin-canary-deployments
  - serverless-stack-output
